### ISSUE TITLE
Impossible de rajouter un utilisateur et modifier les retour code erreur

### ISSUE THREAD

**Issue by neudinger** [KlymbR/api#2]
/auth/register

le retour est :
data and salt arguments required

faire des retour erreur en json:
Http 404 : 
{
"success": false,
"errormsg": "pas trouvé :( "
}

**Comment by neudinger** [comment]
curl -d '{ "id": "10", "password": "toto", "firstName": "Aveli", "lastName": "Docquini", "email": "adocquini@outlook.com", "phone": "+33624350681", "gender": "1","birthdate": "1994-06-28", "licenses": [{ "licenseNbr": "123433", "clubName": "totoScalade", "clubId": "1", "fedId": "1", "endDate": "1994-06-28", "status": "1" }], "address": { "number": "43", "street": "totoStreet", "postalCode": "78800", "city": "Houilles" }, "isAdmin": "false" }' -H "Content-Type: application/json" -X POST http://www.api.klymbr.com/auth/register
{"message":{"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: klymbr.users index: username_1 dup key: { : null }","op":{"address":{"number":43,"street":"totoStreet","postalCode":78800,"city":"Houilles"},"licenses":[{"licenseNbr":"123433","clubName":"totoScalade","clubId":"1","fedId":"1","endDate":"1994-06-28","status":"1"}],"_id":"5af2dc2b57ddb00588299791","id":"10","firstName":"Aveli","lastName":"Docquini","email":"adocquini@outlook.com","phone":"+33624350681","gender":1,"birthdate":"1994-06-28T00:00:00.000Z","isAdmin":false,"hashPassword":"$2a$10$Qeiv2BI0p6at3EALhfFz0uOqQEZO8DGuFwtqkFQsbP9sI7VPB5UTW","createdDate":"2018-05-09T11:31:56.065Z","__v":0}}}

return

{"message":{"error collection: klymbr.users index: username_1 dup key: { : null }","op":{"address":{"number":43,"street":"totoStreet","postalCode":78800,"city":"Houilles"},"licenses":[{"licenseNbr":"123433","clubName":"totoScalade","clubId":"1","fedId":"1","endDate":"1994-06-28","status":"1"}],"_id":"5af2dc2b57ddb00588299791","id":"10","firstName":"Aveli","lastName":"Docquini","email":"adocquini@outlook.com","phone":"+33624350681","gender":1,"birthdate":"1994-06-28T00:00:00.000Z","isAdmin":false,"hashPassword":"$2a$10$Qeiv2BI0p6at3EALhfFz0uOqQEZO8DGuFwtqkFQsbP9sI7VPB5UTW","createdDate":"2018-05-09T11:31:56.065Z","__v":0}}}

**Comment by aveldocquin** [comment]
Vide ta base de données d'utilisateurs avec les indexes et retest c'est fonctionnel de mon côté.
Format des messages:
{
"success": false,
"message": "message d'erreur"
}

**Comment by neudinger** [comment]
il faut que ca fonctionne sur le serveur api.klymbr

**Comment by neudinger** [comment]
curl -d '{ "id": "1", "password": "toto", "firstName": "Avel", "lastName": "Docquin", "email": "adocquin@outlook.com", "phone": "+33624350681", "gender": "1","birthdate": "1994-06-28", "licenses": [{ "licenseNbr": "12343", "clubName": "totoScalade", "clubId": "1", "fedId": "1", "endDate": "1994-06-28", "status": "1" }], "address": { "number": "43", "street": "totoStreet", "postalCode": "78800", "city": "Houilles" }, "isAdmin": "false" }' -H "Content-Type: application/json" -X POST http://www.api.klymbr.com/auth/register

message de retour : 
Created

il faut retourner un json svp

**Comment by neudinger** [comment]
{
"success": true,
"message": "user created"
}

**Comment by neudinger** [comment]
curl -d '{ "id": "4", "password": "tata", "firstName": "kevin", "lastName": "Barre", "email": "kevin@klymbr.com", "phone": "+3342424242", "gender": "1","birthdate": "1994-06-20", "licenses": [{ "licenseNbr": "1233", "clubName": "totoScalade", "clubId": "1", "fedId": "1", "endDate": "1994-06-28", "status": "1" }], "address": { "number": "43", "street": "totoStreet", "postalCode": "78800", "city": "Houilles" }, "isAdmin": "false" }' -H "Content-Type: application/json" -X POST http://www.api.klymbr.com/auth/register

Quand l utilisateur n'a pas dejas ete créé
{"success":true,"message":"Created"}
