### ISSUE TITLE
Lister les utilisateur Not found

### ISSUE THREAD

**Issue by neudinger** [KlymbR/api#7]
/path/user

**Comment by aveldocquin** [comment]
Obtenir l'utilisateur actuel:
localhost:3001/user
[Admin] Obtenir tous les utilisateurs:
localhost:3001/user/all

**Comment by neudinger** [comment]
http://www.api.klymbr.com/user/all/
actuelement
{url: /user/all/ Not Found}

mettre un message explicite si l'utilisateur n as pas le droit de faire cette requête.

401:
{
sucess : false,
message: "not allowed to make this record "
}

curl -H "Content-Type: application/json" -H "Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb2NxdWluQG91dGxvb2suY29tIiwiX2lkIjoiNWFmM2M3MDNjNTlhYzUyZjdhNGMyY2E3IiwiaWF0IjoxNTI1OTI3MTI3fQ.7heG0-Gx5ttEb9YZ_XYscODU1H1Fa98mbmDUKJ5xQNQ" -X GET http://api.klymbr.com/user/all/

{"url":"/user/all/ Not Found"}

**Comment by neudinger** [comment]
Retour d'erreur claire orienter autorisation.

curl -H "Content-Type: application/json" -H "Authorization:JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb2NxdWluQG91dGxvb2suY29tIiwiX2lkIjoiNWFmM2M3MDNjNTlhYzUyZjdhNGMyY2E3IiwiaWF0IjoxNTI1OTI3MTI3fQ.7heG0-Gx5ttEb9YZ_XYscODU1H1Fa98mbmDUKJ5xQNQ" -X GET http://api.klymbr.com/user/all/

Retour
{"success":false,"message":"Unauthorized, is not admin"}
