### ISSUE TITLE
Impossible de se connecter et modifier les retour code erreur

### ISSUE THREAD

**Issue by neudinger** [KlymbR/api#8]
/auth/sign_in/

le retour est :
{"message":"Authentication failed. User not found."}

alors que je ne peux pas crée cet l'utilisateur car deja présent

faire des retour erreur en json:
Http 401 :
{
"success": false,
"errormsg": "Pas encore enregistré le grimpeur"
}

**Comment by aveldocquin** [comment]
Testé et fonctionnel du côté de l'api.
Type des retours:
Http 401 :
{
"success": false,
"message": "Message d'erreur"
}

**Comment by neudinger** [comment]
curl -d '{"email": "adocquin@outlook.com", "password": "toto"}' -H "Content-Type: application/json" -X POST http://www.api.klymbr.com/auth/sign_in/

{"success":true,"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkb2NxdWluQG91dGxvb2suY29tIiwiX2lkIjoiNWFmM2M3MDNjNTlhYzUyZjdhNGMyY2E3IiwiaWF0IjoxNTI1OTI1NzcxfQ.4mZgqdqY-Hfo8Cv7iEb5Ff7DUtf2E4He_VusLyibcAo"}

OK pour moi à ce jour
